### ISSUE TITLE
Issue rendering nested HTML

### ISSUE THREAD

**Issue by stephtr** [probablyup/markdown-to-jsx#168]
Some nested HTML tags don't get rendered correctly. One example is `<div></div><div><div></div></div>`, which gets compiled as `<div> &lt;div&gt; <div></div><div></div></div>`.
It seems to be related to the detection of HTML, since entering `<div>#a</div>` compiles to `<div><h1>a</h1></div>`.
A few versions back markdown-to-jsx compiled those strings correctly.
Just a sidenode: entering `"<span>#a</span>"` crashes the compiler.

**Comment by probablyup** [comment]
Thanks, I'll take a look in the next few days

**Comment by probablyup** [comment]
> Just a sidenote: entering "<span>#a</span>" crashes the compiler.

I'm not seeing that behavior btw - if you pop it into the demo site it works as expected.

**Comment by stephtr** [comment]
> I'm not seeing that behavior btw - if you pop it into the demo site it works as expected.

Did you include the quotation marks and the span? On my machine it crashes the demo site.

**Comment by probablyup** [comment]
Yup, it didn't crash for me.

**Comment by probablyup** [comment]
It's possible you might be viewing a cached, older version of the site?

**Comment by stephtr** [comment]
It is for sure the most recent version offered by the server. But since it doesn't crash my local installation, it can only be an issue of outdated files.

**Comment by stephtr** [comment]
Interestingly if I run https://runkit.com/stephtr/runkit-npm-markdown-to-jsx it runs indefinitely. I will try to debug it if I have some time left.

**Comment by probablyup** [comment]
A fix is pushed in v6.6.1, let me know how it goes!

**Comment by stephtr** [comment]
6.6.1 fixes the crash, however the nested HTML tags still don't render correctly. Additionally, as far as I know, markdown inside HTML inside markdown is only allowed with inline elements, so when given `<div>#a</div>`, markdown-to-jsx should output just `<div>#a</div>`.

**Comment by probablyup** [comment]
There actually are no official rules relating to arbitrary html and
markdown. I try to avoid white lists as much as possible in the code, since
they’re pure bloat.

**Comment by stephtr** [comment]
Actually [there are](https://daringfireball.net/projects/markdown/syntax#html):

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.
> […]
> Unlike block-level HTML tags, Markdown syntax _is_ processed within span-level tags.

Otherwise it wouldn't be possible to start with an hashtag within an element without escaping it. (For example, I would like to display the hex color code.)

**Comment by probablyup** [comment]
Hmm ok. I’ll see if there’s a way to do this without introducing a ton of
bundle size.

**Comment by stephtr** [comment]
Usually when mention such issues I try to help with a PR, but unfortunately at the moment I'm too busy with my other projects.

One approach would be to first convert the whole Markdown code to HTML using an existing parser (which, in contrast to simple-markdown, is able to handle HTML), which would obviate correctly implementing all rules.

**Comment by probablyup** [comment]
Yeah that was my original approach before v6, but the bundle size was
massive. I’ll figure something out.

**Comment by stephtr** [comment]
Ah, I just saw #159. However before keeping the actual state (messed up parsing of HTML) I would revert #156.

**Comment by michaelryancaputo** [comment]
Just for reference, I posted some use cases here: 
This is an example using 6.4.1 - https://stackblitz.com/edit/react-qugqd6
This is an example using 6.6.1 - https://stackblitz.com/edit/react-6nelfr
